#!/bin/sh
echo "Initializing data with $ETHEREUM_GENESIS"
geth --datadir data init $ETHEREUM_GENESIS
echo $ETHEREUM_WALLET > data/keystore/wallet
echo $ETHEREUM_PASSWORD > password.txt
echo "Starting mining"
geth \
--mine \
--datadir data \
--syncmode 'full' \
--port $ETHEREUM_PORT \
--networkid 51132 \
--gasprice '0' \
--unlock $ETHEREUM_ADDRESS \
--password=password.txt \
--rpc \
--rpcapi 'eth,shh,web3,net' \
--rpccorsdomain="*" \
--rpcvhosts '*' \
--rpcaddr '0.0.0.0' \
--rpcport 8545
